package inspect

// The descriptions of the process readings and the per-name accounts.
//
// A file of their own beside the other schemas, because together they are one
// job and the file holding the rest is already the length it should be.

import (
	"github.com/mbauer83/effect-golang-schema/schema"
)

var pointSchema = schema.Struct[Point]("Point",
	schema.FieldOf("atMicros", schema.Int64(),
		func(value Point) int64 { return value.AtMicros },
		func(value *Point, field int64) { value.AtMicros = field }).
		WithDescription("AtMicros is the offset from the first point, so a chart's axis needs no clock."),
	schema.FieldOf("heapBytes", schema.Int64(),
		func(value Point) int64 { return value.HeapBytes },
		func(value *Point, field int64) { value.HeapBytes = field }),
	schema.FieldOf("goroutines", schema.Int64(),
		func(value Point) int64 { return value.Goroutines },
		func(value *Point, field int64) { value.Goroutines = field }),
	schema.FieldOf("runnable", schema.Int64(),
		func(value Point) int64 { return value.Runnable },
		func(value *Point, field int64) { value.Runnable = field }),
	schema.FieldOf("stackBytes", schema.Int64(),
		func(value Point) int64 { return value.StackBytes },
		func(value *Point, field int64) { value.StackBytes = field }),
	schema.FieldOf("goalBytes", schema.Int64(),
		func(value Point) int64 { return value.GoalBytes },
		func(value *Point, field int64) { value.GoalBytes = field }),
	schema.FieldOf("bytesPerSecond", schema.Float64(),
		func(value Point) float64 { return value.BytesPerSecond },
		func(value *Point, field float64) { value.BytesPerSecond = field }),
	schema.FieldOf("busy", schema.Float64(),
		func(value Point) float64 { return value.Busy },
		func(value *Point, field float64) { value.Busy = field }),
).WithDescription("Point is one reading on a chart.")

var processSchema = schema.Struct[Process]("Process",
	schema.FieldOf("sampled", schema.Bool(),
		func(value Process) bool { return value.Sampled },
		func(value *Process, field bool) { value.Sampled = field }).
		WithDescription("Sampled says a reading was taken; without a series there is nothing to report and two zeroes would read as a program using nothing."),
	schema.FieldOf("heapBytes", schema.Int64(),
		func(value Process) int64 { return value.HeapBytes },
		func(value *Process, field int64) { value.HeapBytes = field }),
	schema.FieldOf("heapObjects", schema.Int64(),
		func(value Process) int64 { return value.HeapObjects },
		func(value *Process, field int64) { value.HeapObjects = field }),
	schema.FieldOf("liveBytes", schema.Int64(),
		func(value Process) int64 { return value.LiveBytes },
		func(value *Process, field int64) { value.LiveBytes = field }),
	schema.FieldOf("goalBytes", schema.Int64(),
		func(value Process) int64 { return value.GoalBytes },
		func(value *Process, field int64) { value.GoalBytes = field }).
		WithDescription("GoalBytes is the heap size the next collection is aiming at."),
	schema.FieldOf("stackBytes", schema.Int64(),
		func(value Process) int64 { return value.StackBytes },
		func(value *Process, field int64) { value.StackBytes = field }),
	schema.FieldOf("totalBytes", schema.Int64(),
		func(value Process) int64 { return value.TotalBytes },
		func(value *Process, field int64) { value.TotalBytes = field }),
	schema.FieldOf("goroutines", schema.Int64(),
		func(value Process) int64 { return value.Goroutines },
		func(value *Process, field int64) { value.Goroutines = field }),
	schema.FieldOf("running", schema.Int64(),
		func(value Process) int64 { return value.Running },
		func(value *Process, field int64) { value.Running = field }),
	schema.FieldOf("runnable", schema.Int64(),
		func(value Process) int64 { return value.Runnable },
		func(value *Process, field int64) { value.Runnable = field }).
		WithDescription("Runnable is ready and not running: a goroutine waiting for a thread rather than for work."),
	schema.FieldOf("waiting", schema.Int64(),
		func(value Process) int64 { return value.Waiting },
		func(value *Process, field int64) { value.Waiting = field }),
	schema.FieldOf("threads", schema.Int64(),
		func(value Process) int64 { return value.Threads },
		func(value *Process, field int64) { value.Threads = field }),
	schema.FieldOf("gcCycles", schema.Int64(),
		func(value Process) int64 { return value.GCCycles },
		func(value *Process, field int64) { value.GCCycles = field }),
	schema.FieldOf("overMicros", schema.Int64(),
		func(value Process) int64 { return value.OverMicros },
		func(value *Process, field int64) { value.OverMicros = field }),
	schema.FieldOf("allocBytes", schema.Int64(),
		func(value Process) int64 { return value.AllocBytes },
		func(value *Process, field int64) { value.AllocBytes = field }),
	schema.FieldOf("bytesPerSecond", schema.Float64(),
		func(value Process) float64 { return value.BytesPerSecond },
		func(value *Process, field float64) { value.BytesPerSecond = field }),
	schema.FieldOf("busy", schema.Float64(),
		func(value Process) float64 { return value.Busy },
		func(value *Process, field float64) { value.Busy = field }).
		WithDescription("Busy is the share of the available CPU the process used, measured against the threads it was allowed."),
	schema.FieldOf("gcShare", schema.Float64(),
		func(value Process) float64 { return value.GCShare },
		func(value *Process, field float64) { value.GCShare = field }).
		WithDescription("Collecting is the share of the CPU it used that the collector took."),
	schema.FieldOf("points", schema.List(pointSchema),
		func(value Process) []Point { return value.Points },
		func(value *Process, field []Point) { value.Points = field }),
).WithDescription("Process is what the program is spending, process-wide.")

var costSchema = schema.Struct[Cost]("Cost",
	schema.FieldOf("name", schema.Text(),
		func(value Cost) string { return value.Name },
		func(value *Cost, field string) { value.Name = field }),
	schema.FieldOf("times", schema.Int64(),
		func(value Cost) int64 { return value.Times },
		func(value *Cost, field int64) { value.Times = field }),
	schema.FieldOf("bytesDuring", schema.Int64(),
		func(value Cost) int64 { return value.BytesDuring },
		func(value *Cost, field int64) { value.BytesDuring = field }).
		WithDescription("AllocatedDuring is what the process allocated while the work ran, which on a busy program includes whatever else ran."),
	schema.FieldOf("perRunBytes", schema.Int64(),
		func(value Cost) int64 { return value.PerRunBytes },
		func(value *Cost, field int64) { value.PerRunBytes = field }),
	schema.FieldOf("bytesP50", schema.Int64(),
		func(value Cost) int64 { return value.BytesP50 },
		func(value *Cost, field int64) { value.BytesP50 = field }).
		WithDescription("AllocatedP50Bytes is what a typical run of this name allocated: a measurement that happened, read from the runs the account kept."),
	schema.FieldOf("bytesP95", schema.Int64(),
		func(value Cost) int64 { return value.BytesP95 },
		func(value *Cost, field int64) { value.BytesP95 = field }),
	schema.FieldOf("bytesP99", schema.Int64(),
		func(value Cost) int64 { return value.BytesP99 },
		func(value *Cost, field int64) { value.BytesP99 = field }),
	schema.FieldOf("objectsP95", schema.Int64(),
		func(value Cost) int64 { return value.ObjectsP95 },
		func(value *Cost, field int64) { value.ObjectsP95 = field }),
	schema.FieldOf("sampleSize", schema.Int64(),
		func(value Cost) int64 { return value.SampleSize },
		func(value *Cost, field int64) { value.SampleSize = field }).
		WithDescription("KeptRuns is how many runs the quantiles are drawn from: a ninety-ninth percentile over three runs is a sentence with no content."),
	schema.FieldOf("objectsPerRun", schema.Int64(),
		func(value Cost) int64 { return value.ObjectsPerRun },
		func(value *Cost, field int64) { value.ObjectsPerRun = field }).
		WithDescription("ObjectsPerRun is how many allocations a run made, which in Go is usually more actionable than their weight."),
	schema.FieldOf("meanObjectBytes", schema.Int64(),
		func(value Cost) int64 { return value.MeanObjectBytes },
		func(value *Cost, field int64) { value.MeanObjectBytes = field }),
	schema.FieldOf("sizes", schema.List(sizeClassSchema),
		func(value Cost) []SizeClass { return value.Sizes },
		func(value *Cost, field []SizeClass) { value.Sizes = field }).
		WithDescription("Sizes are the size classes the allocations fell into, smallest first, or empty when the account was not told to keep them."),
	schema.FieldOf("cpuSecondsDuring", schema.Float64(),
		func(value Cost) float64 { return value.CPUSecondsDuring },
		func(value *Cost, field float64) { value.CPUSecondsDuring = field }),
	schema.FieldOf("longestMicros", schema.Int64(),
		func(value Cost) int64 { return value.LongestMicros },
		func(value *Cost, field int64) { value.LongestMicros = field }),
	schema.FieldOf("collections", schema.Int64(),
		func(value Cost) int64 { return value.Collections },
		func(value *Cost, field int64) { value.Collections = field }),
	schema.FieldOf("runs", schema.List(runSchema),
		func(value Cost) []Run { return value.Runs },
		func(value *Cost, field []Run) { value.Runs = field }).
		WithDescription("Runs are the recent runs of this name, newest first: what one span did, where the figures beside them are what the name costs on average."),
).WithDescription("Cost is what the process spent while one name's work ran.")

var runSchema = schema.Struct[Run]("Run",
	schema.FieldOf("endMicros", schema.Int64(),
		func(value Run) int64 { return value.EndMicros },
		func(value *Run, field int64) { value.EndMicros = field }).
		WithDescription("EndedMicros is the offset from the earliest span in this reading, so a run can be matched to the span whose window it ended in."),
	schema.FieldOf("micros", schema.Int64(),
		func(value Run) int64 { return value.Micros },
		func(value *Run, field int64) { value.Micros = field }),
	schema.FieldOf("bytes", schema.Int64(),
		func(value Run) int64 { return value.Bytes },
		func(value *Run, field int64) { value.Bytes = field }),
	schema.FieldOf("objects", schema.Int64(),
		func(value Run) int64 { return value.Objects },
		func(value *Run, field int64) { value.Objects = field }),
).WithDescription("Run is one run of a name: when its window ended, and what the process did during it.")

var sizeClassSchema = schema.Struct[SizeClass]("SizeClass",
	schema.FieldOf("atMostBytes", schema.Int64(),
		func(value SizeClass) int64 { return value.AtMostBytes },
		func(value *SizeClass, field int64) { value.AtMostBytes = field }).
		WithDescription("AtMostBytes is the class's upper edge, and zero for the widest class, which has none."),
	schema.FieldOf("count", schema.Int64(),
		func(value SizeClass) int64 { return value.Count },
		func(value *SizeClass, field int64) { value.Count = field }),
).WithDescription("SizeClass is one of Go's allocation size classes.")
