package inspect

// The descriptions of the process readings and the per-name accounts.
//
// A file of their own beside the other schemas, because together they are one
// job and the file holding the rest is already the length it should be.

import (
	"github.com/mbauer83/effect-golang-schema/schema"
)

var pointSchema = schema.Struct[Point]("Point",
	schema.FieldOf("atMicros", schema.Int64(),
		func(value Point) int64 { return value.AtMicros },
		func(value *Point, field int64) { value.AtMicros = field }).
		Documented("AtMicros is the offset from the first point, so a chart's axis needs no clock."),
	schema.FieldOf("heapBytes", schema.Int64(),
		func(value Point) int64 { return value.HeapBytes },
		func(value *Point, field int64) { value.HeapBytes = field }),
	schema.FieldOf("goroutines", schema.Int64(),
		func(value Point) int64 { return value.Goroutines },
		func(value *Point, field int64) { value.Goroutines = field }),
	schema.FieldOf("runnable", schema.Int64(),
		func(value Point) int64 { return value.Runnable },
		func(value *Point, field int64) { value.Runnable = field }),
	schema.FieldOf("stackBytes", schema.Int64(),
		func(value Point) int64 { return value.StackBytes },
		func(value *Point, field int64) { value.StackBytes = field }),
	schema.FieldOf("goalBytes", schema.Int64(),
		func(value Point) int64 { return value.GoalBytes },
		func(value *Point, field int64) { value.GoalBytes = field }),
	schema.FieldOf("bytesPerSecond", schema.Float64(),
		func(value Point) float64 { return value.BytesPerSecond },
		func(value *Point, field float64) { value.BytesPerSecond = field }),
	schema.FieldOf("busy", schema.Float64(),
		func(value Point) float64 { return value.Busy },
		func(value *Point, field float64) { value.Busy = field }),
).Documented("Point is one reading on a chart.")

var processSchema = schema.Struct[Process]("Process",
	schema.FieldOf("sampled", schema.Bool(),
		func(value Process) bool { return value.Sampled },
		func(value *Process, field bool) { value.Sampled = field }).
		Documented("Sampled says a reading was taken; without a series there is nothing to report and two zeroes would read as a program using nothing."),
	schema.FieldOf("heapBytes", schema.Int64(),
		func(value Process) int64 { return value.HeapBytes },
		func(value *Process, field int64) { value.HeapBytes = field }),
	schema.FieldOf("heapObjects", schema.Int64(),
		func(value Process) int64 { return value.HeapObjects },
		func(value *Process, field int64) { value.HeapObjects = field }),
	schema.FieldOf("liveBytes", schema.Int64(),
		func(value Process) int64 { return value.LiveBytes },
		func(value *Process, field int64) { value.LiveBytes = field }),
	schema.FieldOf("goalBytes", schema.Int64(),
		func(value Process) int64 { return value.GoalBytes },
		func(value *Process, field int64) { value.GoalBytes = field }).
		Documented("GoalBytes is the heap size the next collection is aiming at."),
	schema.FieldOf("stackBytes", schema.Int64(),
		func(value Process) int64 { return value.StackBytes },
		func(value *Process, field int64) { value.StackBytes = field }),
	schema.FieldOf("totalBytes", schema.Int64(),
		func(value Process) int64 { return value.TotalBytes },
		func(value *Process, field int64) { value.TotalBytes = field }),
	schema.FieldOf("goroutines", schema.Int64(),
		func(value Process) int64 { return value.Goroutines },
		func(value *Process, field int64) { value.Goroutines = field }),
	schema.FieldOf("running", schema.Int64(),
		func(value Process) int64 { return value.Running },
		func(value *Process, field int64) { value.Running = field }),
	schema.FieldOf("runnable", schema.Int64(),
		func(value Process) int64 { return value.Runnable },
		func(value *Process, field int64) { value.Runnable = field }).
		Documented("Runnable is ready and not running: a goroutine waiting for a thread rather than for work."),
	schema.FieldOf("waiting", schema.Int64(),
		func(value Process) int64 { return value.Waiting },
		func(value *Process, field int64) { value.Waiting = field }),
	schema.FieldOf("threads", schema.Int64(),
		func(value Process) int64 { return value.Threads },
		func(value *Process, field int64) { value.Threads = field }),
	schema.FieldOf("gcCycles", schema.Int64(),
		func(value Process) int64 { return value.GCCycles },
		func(value *Process, field int64) { value.GCCycles = field }),
	schema.FieldOf("overMicros", schema.Int64(),
		func(value Process) int64 { return value.OverMicros },
		func(value *Process, field int64) { value.OverMicros = field }),
	schema.FieldOf("allocatedBytes", schema.Int64(),
		func(value Process) int64 { return value.AllocatedBytes },
		func(value *Process, field int64) { value.AllocatedBytes = field }),
	schema.FieldOf("bytesPerSecond", schema.Float64(),
		func(value Process) float64 { return value.BytesPerSecond },
		func(value *Process, field float64) { value.BytesPerSecond = field }),
	schema.FieldOf("busy", schema.Float64(),
		func(value Process) float64 { return value.Busy },
		func(value *Process, field float64) { value.Busy = field }).
		Documented("Busy is the share of the available CPU the process used, measured against the threads it was allowed."),
	schema.FieldOf("collecting", schema.Float64(),
		func(value Process) float64 { return value.Collecting },
		func(value *Process, field float64) { value.Collecting = field }).
		Documented("Collecting is the share of the CPU it used that the collector took."),
	schema.FieldOf("points", schema.List(pointSchema),
		func(value Process) []Point { return value.Points },
		func(value *Process, field []Point) { value.Points = field }),
).Documented("Process is what the program is spending, process-wide.")

var costSchema = schema.Struct[Cost]("Cost",
	schema.FieldOf("name", schema.Text(),
		func(value Cost) string { return value.Name },
		func(value *Cost, field string) { value.Name = field }),
	schema.FieldOf("times", schema.Int64(),
		func(value Cost) int64 { return value.Times },
		func(value *Cost, field int64) { value.Times = field }),
	schema.FieldOf("allocatedDuring", schema.Int64(),
		func(value Cost) int64 { return value.AllocatedDuring },
		func(value *Cost, field int64) { value.AllocatedDuring = field }).
		Documented("AllocatedDuring is what the process allocated while the work ran, which on a busy program includes whatever else ran."),
	schema.FieldOf("perRunBytes", schema.Int64(),
		func(value Cost) int64 { return value.PerRunBytes },
		func(value *Cost, field int64) { value.PerRunBytes = field }),
	schema.FieldOf("cpuSecondsDuring", schema.Float64(),
		func(value Cost) float64 { return value.CPUSecondsDuring },
		func(value *Cost, field float64) { value.CPUSecondsDuring = field }),
	schema.FieldOf("longestMicros", schema.Int64(),
		func(value Cost) int64 { return value.LongestMicros },
		func(value *Cost, field int64) { value.LongestMicros = field }),
	schema.FieldOf("collections", schema.Int64(),
		func(value Cost) int64 { return value.Collections },
		func(value *Cost, field int64) { value.Collections = field }),
).Documented("Cost is what the process spent while one name's work ran.")
